### ISSUE TITLE
Cool app, so how do you use it?

### ISSUE THREAD

**Issue by tomdevlive** [mariokaufmann/zagreus#109]
So this looks pretty cool, but I cant find any detailed documentaion for working creating animations, and wokring with them I did check out the swagger.

**Comment by tomdevlive** [comment]
Ok scratch that, just saw the Docs folder with tons of info!

**Comment by mariokaufmann** [comment]
Hi @tomdevlive . Thanks for your interest in the project. Unfortunately the timing is a bit unlucky, as I just switched up the  architecture from svg-based templates to just plain html/css templates and the documentation is not updated yet.
So the examples that are in the docs folder are unfortunately outdated. So while they still work with the latest release version they won't be valid anymore for the next one. I will hopefully get to updating those asap.
In the meantime, you could have a look at the [example template](https://github.com/mariokaufmann/zagreus/blob/main/e2e-test/template/index.html) that we use for testing. It reflects how templates can be created with the zagreus version from the main branch (which will be the next release version)

**Comment by tomdevlive** [comment]
Ok no worries. I'll check back in a bit to see how things are going, in the meantime I will take a look at the link you sent. Thanks again!

**Comment by mariokaufmann** [comment]
The docs are now updated. While still quite rough around the edges they should outline the basic steps on how to get everything to work together. They also match the newest version 0.0.8 that was just released. Let me know if any issues crop up!
